async function successOrErrors(key) {
	/**
	 *ERROR PARAMETER
	 */
	var parameters = {
		bannerId: "bannerId",
		bannerImage: "bannerImage",
		language: "language",
		fullName: "fullName",
		arabicName: "arabicName",
		noParams: "",
		page: "page",
		email: "email",
		appleId: "appleId",
		notesId: "notesId",
		username: "username",
		password: "password",
		confirmPass: "confirmPassword",
		retypePassword: "retypePassword",
		newPassword: "newPassword",
		changePassword: "changePassword",
		retypePassword: "retypePassword",
		confirmPassword: "password or confirmPassword",
		userId: "userId",
		deactivate: "deactivate",
		mobileNumber: "mobileNumber",
		newPassword: "newPassword",
		currentPassword: "currentPassword",
		deviceRequire: " deviceType, fcmToken, deviceId ",
		loginType: "loginType",
		countryCode: "countryCode",
		deviceType: "deviceType",
		deviceToken: "deviceToken",
		deviceTokenVoIP: "deviceTokenVoIP",
		deviceId: "deviceId",
		firstName: "firstName",
		lastName: "lastName",
		adminId: "adminId",
		facebookId: "facebookId",
		role: "role",
		user: "user",
		address: "address",
		name: "name",
		reason: "reason",
		status: "status",
		isBlock: "isBlock",
		isEmailVerified: "isEmailVerified",
		liveChatFlag: "liveChatFlag",
		liveAudioCallFlag: "liveAudioCallFlag",
		liveVideoCallFlag: "liveVideoCallFlag",
		textFlag: "textFlag",
		action: "action",
		user: "user",
		blockUserId: "blockUserId",
		reportUserId: "reportUserId",
		pageKey: "pageKey",
		pageTitle: "pageTitle",
		content: "content",
		update: "update",
		cmsId: "cmsId",
		currentAppVersion: "currentAppVersion",
		androidForseUpdate: "androidForseUpdate",
		iOSForseUpdate: "iOSForseUpdate",
		androidVersion: "androidVersion",
		iOSVersion: "iOSVersion",
		appVersion: "appVersion",
		currentVersion: "currentVersion",
		otp: "otp",
		mail: "mail",
		note: "note",
		socketId: "socketId",
		sendBy: "sendBy",
		loginUser: "loginUser",
		uuid: "uuid",
		isVideo: "isVideo",
		connect: "connect",
		token: "token",
		uid: "uid",
		nickName: "nickName",
		civilId: "civilId",
		heading: "heading",
		dob: "dob",
		city: "city",
		country: "country",
		emergencyContactNo: "emergencyContactNo",
		linkedinId: "linkedinId",
		googleId: "googleId",
		description: "description",
		qualifications: "qualifications",
		university: "university",
		specialization: "specialization",
		workExperience: "workExperience",
		employmentHistory: "employmentHistory",
		noOfYears: "noOfYears",
		therapyOfferType: "therapyOfferType",
		accountName: "accountName",
		accountNo: "accountNo",
		bankName: "bankName",
		branchAddress: "branchAddress",
		ibanNo: "ibanNo",
		typeofAccount: "typeofAccount",
		therapyId: "therapyId",
		government: "government",
		educational: "educational",
		languageId: "languageId",
		gender: "gender",
		addTherapies: "therapies",
		patientId: "patientId",
		therapistId: "therapistId",
		typeofInteraction: "typeofInteraction",
		startTimeSlot: "startTimeSlot",
		appointmentDate: "appointmentDate",
		emergencyNumber: "emergencyNumber",
		eCountryCode: "eCountryCode",
		dayOfWeek: "dayOfWeek",
		leaveDate: "leaveDate",
		sessionSummary: "sessionSummary",
		feedback: "feedback",
		appointmentId: "appointmentId",
		voIpToken: "voIpToken",
		timezone: "timezone",
		loginUserId: "loginUserId",
		chatUserId: "chatUserId",
		senderId: "senderId",
		receiverId: "receiverId",
		history: "logged_user_id & chat_user_id",
		utcStartTime: "utcStartTime",
		utcEndTime: "utcEndTime",
		notification: "notification",
		leaveStartDate: "leaveStartDate",
		paymentId: "paymentId",
		paymentStatus: "paymentStatus",
		rating: "rating",
		questionAbout: "questionAbout",
		userType: "userType",
		therapi: "therapiName",
		therapiImage: "therapiImage",
		therapiId: "therapiId",
		reportId: "reportId",
		homeWork: "homeWork",
		topicQuestions: "topicQuestions",
		comments: "comments",
		interventionNeeded: "interventionNeeded",
		phone: "phone",
		isAppointments: "isAppointments",
	};

	/**
	 * SUCCESS MESSAGE
	 */
	var successMessages = {
		languages: "Languages get successfully",
		roleResources: "Role resources get successfully",
		success: "succes",
		login: "Login successful",
		register: "Registration successful",
		getall: "Therapies get successfully",
		getDoctors: "Doctors get successfully",
		updateDoctors: "Admin updated doctor successfully",
		getPatients: "Patients get successfully",
		adminGetAll: "Admin data get successfully",
		update: "Therapies data updated successfully",
		adminUpdate: "Admin data updated successfully",
		updatePassword: "User password updated succesfully",
		updatePatient: "Patient data updated successfully",
		logout: "User logout successful ",
		get: "User exists",
		getNotes: "All notes get successfully",
		updateNotes: "Note updated Successfully",
		notificationEnable: "User notification enabled successfully",
		notificationDisable: "User notification disabled successfully",
		unblock: "User activated successfully",
		inComplete: "Changes requested successfully",
		block: "User deleted successfully",
		decline: "User Declined Successfully",
		delete: "User deleted successfully",
		addNotes: "Note added successfully",
		deleteNotes: "Note deleted successfully",
		adminDelete: "Admin deleted successfully",
		getDoctor: "Single therapist get successfully",
		getPatient: "Single patient get successfully",
		languageCreate: "Language create successfully",
		languageUpdate: "Language data updated successfully",
		languageDelete: "Language data deleted successfully",
		forgotPassword:
			"You will receive email regarding resetting your password, if you are registered with us.",
		getCms: "CMS data get successfully",
		updateCms: "CMS data updated successfully",
		addCms: "CMS data added successfully",
		deleteDocument: "Document deleted successfully",
		getUsers: "Users get successfully",
		addDoctor: "Admin create doctor successfully",
		addAppointment: "Appointment book successfully",
		slots: "available slots get successfully",
		getallCity: "get all city successfully",
		suspend: "Admin suspended doctor successfully",
		unSuspend: "Admin unsuspended doctor successfully",
		addWorkDays: "Date added successfully",
		addLeaveDays: "Leave date added successfully",
		slotsNotAvailable: "Slots not available",
		contactUs: "Contact Us form send successfully",
		contactUsGet: "Contact Us data get successfully",
		feedback: "Feedback send successfully",
		feedbackGet: "feedback data get successfully",
		notAvailable: "Doctor leave dates get successfully",
		therapist: "Get therapist data get successfully",
		appointments: "Get all appointments successfully",
		rescheduleAppointment: "Appointment reschedule successfully",
		msgSent: "Message has been Sent Successfully",
		chatusers: "Fetched Chat User List Successfully",
		chatHist: "Chat History Fetched Successfully",
		lastseen: "Last Seen Fetched Successfully",
		updateSocket: "SocketId Updated Successfully",
		AddChat: "Added to Chat Successfully",
		OnlineStatus: "Online status get successfully",
		cancleAppointment: "Appointment cancel successfully",
		serviceStatus: "Appointment service status update successfully",
		timer: "Timer status get successfully",
		getConnectStatus: "Connect status get successfully",
		disconnectSuccess: "Disconnected successfully",
		OfflineStatus: "Offline status get successfully",
		paymentSuccess: "Payment done successfully",
		paymentFailed: "Payment failed, please try again.",
		linkExpired: "Payment link is expired",
		invoice: "Invoice get successfully",
		transactions: "All transactions get successfully",
		notificationGet: "All notifications get successfully",
		addReviews: "Reviews added successfully",
		reviews: "All Reviews get successfully",
		addbanner: "Banner added successfully",
		banners: "All banners get successfully",
		deleteBanner: "Banner deleted successfully",
		deleteTherapy: "Therapy deleted successfully",
		addTherapy: "Therapy added successfully",
		updateTherapy: "Therapy Updated Successfully",
		addreport: "Report added successfully",
		deleteReport: "Report deleted successfully",
		getReport: "Report data get successfully",
		reports: "All reports get successfully",
		otp: "OTP sent successfully",
		enableConsultNow: "ConsultNow enabled successfully",
		disableConsultNow: "ConsultNow disabled successfully",
	};

	/**
	 * ERROR OBJECT
	 */
	var obj = {
		successMessage: successMessages,
		ex_00: {
			code: "ex_00",
			failMsg: "Exception",
			message: "exception",
			parameters: parameters,
			location: "params",
		},
		err_02: {
			code: "err_02",
			failMsg: "InvalidDetails",
			message: "Please enter required details",
			parameters: parameters,
			location: "body",
		},
		err_03: {
			code: "err_03",
			failMsg: "InvalidEmail",
			message: "Please enter valid email",
			parameters: parameters,
			location: "body",
		},
		err_04: {
			code: "err_04",
			failMsg: "AlreadyExists",
			message: "Email address already exists",
			parameters: parameters,
			location: "body",
		},
		err_05: {
			code: "err_05",
			failMsg: "AlreadyExists",
			message: "Emergency mobile number already exists",
			parameters: parameters,
			location: "body",
		},
		err_06: {
			code: "err_06",
			failMsg: "NoDataFound",
			message: "Therapi data not found",
			parameters: parameters,
			location: "body",
		},
		err_07: {
			code: "err_07",
			failMsg: "InvalidDetails",
			message: "Field contains only characters",
			parameters: parameters,
			location: "body",
		},
		err_08: {
			code: "err_08",
			failMsg: "InvalidDetails",
			message: "Please enter valid IBAN number",
			parameters: parameters,
			location: "body",
		},
		err_09: {
			code: "err_09",
			failMsg: "AppleIdAlreadyExists",
			message: "AppleId already exists",
			parameters: parameters,
			location: "body",
		},
		err_10: {
			code: "err_10",
			failMsg: "InvalidAppleId",
			message: "Please enter apple id",
			parameters: parameters,
			location: "body",
		},
		err_11: {
			code: "err_11",
			failMsg: "InvalidDetails",
			message: "Please upload .pdf file",
			parameters: parameters,
			location: "body",
		},
		err_12: {
			code: "err_12",
			failMsg: "InvalidCredentials",
			message: "Invalid Credentials",
			parameters: parameters,
			location: "body",
		},
		err_13: {
			code: "err_13",
			failMsg: "PasswordsNotMatch",
			message: "NewPassword and ConfirmPssword doesn't match",
			parameters: parameters,
			location: "body",
		},
		err_14: {
			code: "err_14",
			failMsg: "InvalidPhoneNumber",
			message: "Please enter valid phone number",
			parameters: parameters,
			location: "body",
		},
		err_15: {
			code: "err_15",
			failMsg: "InvalidAccountNumber",
			message: "Please enter valid account number",
			parameters: parameters,
			location: "body",
		},
		err_16: {
			code: "err_16",
			failMsg: "TherapiNotFound",
			message: "Therapi Details not found",
			parameters: parameters,
			location: "body",
		},
		err_17: {
			code: "err_1",
			failMsg: "AlreadyExists",
			message: "Account Number already exists",
			parameters: parameters,
			location: "body",
		},
		err_18: {
			code: "err_18",
			failMsg: "AlreadyExists",
			message: "IBAN Number is already exists",
			parameters: parameters,
			location: "body",
		},
		err_19: {
			code: "err_19",
			failMsg: "DataNotFound",
			message: "User details not found",
			parameters: parameters,
			location: "params",
		},
		err_20: {
			code: "err_20",
			failMsg: "IncorrectDetails",
			message: "Incorrect login credentials",
			parameters: parameters,
			location: "body",
		},
		err_21: {
			code: "err_21",
			failMsg: "InvalidDetails",
			message: "Invalid username.",
			parameters: parameters,
			location: "body",
		},
		err_22: {
			code: "err_22",
			failMsg: "AlreadyExists",
			message: "Username already exists",
			parameters: parameters,
			location: "body",
		},
		err_23: {
			code: "err_23",
			failMsg: "InvalidDetails",
			message: "Please enter valid therapistId",
			parameters: parameters,
			location: "params",
		},
		err_24: {
			code: "err_24",
			failMsg: "InvalidDetails",
			message: "Please provide document .pdf format only",
			parameters: parameters,
			location: "body",
		},
		err_25: {
			code: "err_25",
			failMsg: "IncorrectDetails",
			message: "Incorrect apple id, Please enter registered apple id",
			parameters: parameters,
			location: "body",
		},
		err_26: {
			code: "err_26",
			failMsg: "IncorrectDetails",
			message: "Incorrect facebook id, Please enter registered facebook id",
			parameters: parameters,
			location: "body",
		},
		err_27: {
			code: "err_27",
			failMsg: "InvalidDetails",
			message: "Please enter valid login details",
			parameters: parameters,
			location: "body",
		},
		err_28: {
			code: "err_28",
			failMsg: "InvalidDetails",
			message: "Please provide document .jpg,.jprg,.pdf format only",
			parameters: parameters,
			location: "body",
		},
		err_29: {
			code: "err_29",
			failMsg: "InvalidDetails",
			message: "Please provide document .jpg,.jprg,.png format only",
			parameters: parameters,
			location: "body",
		},
		err_30: {
			code: "err_30",
			failMsg: "InvalidDetails",
			message: "Something went wrong",
			parameters: parameters,
			location: "body",
		},
		err_31: {
			code: "err_31",
			failMsg: "InvalidDetails",
			message: "Please provide valid logintype ex. 0: email,1:googleId,2:appleId ,3:facebookId",
			parameters: parameters,
			location: "body",
		},
		err_32: {
			code: "err_32",
			failMsg: "invalidUserId",
			message: "Please enter valid user id",
			parameters: parameters,
			location: "params",
		},
		err_33: {
			code: "err_33",
			failMsg: "NotMatchPasswords",
			message: "Current password doesn't match",
			parameters: parameters,
			location: "body",
		},
		err_34: {
			code: "err_34",
			failMsg: "InvalidDetails",
			message: "Please enter new password",
			parameters: parameters,
			location: "body",
		},
		err_35: {
			code: "err_35",
			failMsg: "InvalidDetails",
			message: "Please provide valid device type",
			parameters: parameters,
			location: "body",
		},
		err_36: {
			code: "err_36",
			failMsg: "NotesNotFound",
			message: "Notes not found",
			parameters: parameters,
			location: "body",
		},
		err_37: {
			code: "err_37",
			failMsg: "InvalidDetails",
			message: "Please enter confirm new password",
			parameters: parameters,
			location: "body",
		},
		err_38: {
			code: "err_38",
			failMsg: "InvalidDetails",
			message: "Please provide valid login type 0 or 1,2,3",
			parameters: parameters,
			location: "body",
		},
		err_39: {
			code: "err_39",
			failMsg: "DataNotFound",
			message: "Notes details not found",
			parameters: parameters,
			location: "params",
		},
		err_40: {
			code: "err_40",
			failMsg: "InvalidDetails",
			message: "Please enter valid country code",
			parameters: parameters,
			location: "body",
		},
		err_41: {
			code: "err_41",
			failMsg: "AlreadyExists",
			message: "Mobile number already exists",
			parameters: parameters,
			location: "body",
		},
		err_42: {
			code: "err_42",
			failMsg: "AlreadyExists",
			message: "Email is already exists",
			parameters: parameters,
			location: "body",
		},
		err_43: {
			code: "err_43",
			failMsg: "InvalidDetails",
			message: "Invalid first name, allowed only letters, space, _, ', (), dot and comma",
			parameters: parameters,
			location: "body",
		},
		err_44: {
			code: "err_44",
			failMsg: "InvalidDetails",
			message: "Invalid last name, allowed only letters, space, _, ', (), dot and comma",
			parameters: parameters,
			location: "body",
		},
		err_45: {
			code: "err_45",
			failMsg: "Deactivateduser",
			message: "Deactivated user",
			parameters: parameters,
			location: "",
		},
		err_46: {
			code: "err_46",
			failMsg: "InvalidPassword",
			message:
				"Password should be 8 characters long,including at least one upper case,lower case,special character and one digit",
			parameters: parameters,
			location: "",
		},
		err_47: {
			code: "err_13",
			failMsg: "PasswordsNotMatch",
			message: "changePassword and retypePassword doesn't match",
			parameters: parameters,
			location: "body",
		},
		err_48: {
			code: "err_48",
			failMsg: "invalidUserId",
			message: "Please enter valid notes id",
			parameters: parameters,
			location: "params",
		},
		err_49: {
			code: "err_49",
			failMsg: "IncorrectDetails",
			message: "Incorrect password, Please try again",
			parameters: parameters,
			location: "body",
		},
		err_50: {
			code: "err_50",
			failMsg: "Incorrect Details",
			message: "Educational certificates not uploaded ",
			parameters: parameters,
			location: "body",
		},
		err_51: {
			code: "err_51",
			failMsg: "Incorrect Details",
			message: "You have already register as ",
			parameters: parameters,
			location: "body",
		},
		err_52: {
			code: "err_52",
			failMsg: "PendingApproval",
			message: "Your request is pending for Admin Approval ",
			parameters: parameters,
			location: "",
		},
		err_54: {
			code: "err_54",
			failMsg: "InvalidDetails",
			message: "Please enter valid date (dd-mm-yyyy)",
			parameters: parameters,
			location: "body",
		},
		err_55: {
			code: "err_55",
			failMsg: "invalidDocumnetId",
			message: "Please enter valid document id",
			parameters: parameters,
			location: "params",
		},
		err_56: {
			code: "err_56",
			failMsg: "noDataFound",
			message: "Document not found",
			parameters: parameters,
			location: "params",
		},
		err_57: {
			code: "err_57",
			failMsg: "InvalidDetails",
			message: "Please enter valid admin id",
			parameters: parameters,
			location: "body",
		},
		err_58: {
			code: "err_58",
			failMsg: "InvalidDetails",
			message: "Please enter valid gender value 1,2,3",
			parameters: parameters,
			location: "body",
		},
		err_59: {
			code: "err_59",
			failMsg: "InvalidDetails",
			message: "Please enter valid patient Id",
			parameters: parameters,
			location: "body",
		},
		err_60: {
			code: "err_60",
			failMsg: "DeclinedByAdmin",
			message: "Your account is declined by Admin",
			parameters: parameters,
			location: "body",
		},
		err_61: {
			code: "err_61",
			failMsg: "InvalidDetails",
			message: "Please select valid typeofInteraction 0:Text,1:Voice,2:Video",
			parameters: parameters,
			location: "body",
		},
		err_62: {
			code: "err_62",
			failMsg: "notAvailable",
			message: "Slot is not available",
			parameters: parameters,
			location: "body",
		},
		err_63: {
			code: "err_63",
			failMsg: "notAvailable",
			message: "Therapist is not available",
			parameters: parameters,
			location: "body",
		},
		err_64: {
			code: "err_64",
			failMsg: "Required details ",
			message: "Please provide firstName and lastName or nickName",
			parameters: parameters,
			location: "body",
		},
		err_65: {
			code: "err_65",
			failMsg: "InvalidDetails",
			message: "Please enter valid date Ex.2023-04-05T18:30:00.000Z format",
			parameters: parameters,
			location: "body",
		},
		err_66: {
			code: "err_66",
			failMsg: "InvalidDetails",
			message: "Please enter valid appointmentId",
			parameters: parameters,
			location: "body",
		},
		err_67: {
			code: "err_67",
			failMsg: "InvalidDetails",
			message: "Appointment details not found",
			parameters: parameters,
			location: "body",
		},
		err_68: {
			code: "err_68",
			failMsg: "InvalidDetails",
			message: "Please add work days first",
			parameters: parameters,
			location: "body",
		},
		err_69: {
			code: "err_69",
			failMsg: "InvalidDetails",
			message: "Please enter valid patientId",
			parameters: parameters,
			location: "body",
		},
		err_70: {
			code: "err_70",
			failMsg: "InvalidDetails",
			message: "Please enter valid paymentStatus",
			parameters: parameters,
			location: "body",
		},
		err_74: {
			code: "err_74",
			failMsg: "InvalidDetails",
			message: "Please enter valid role 0 or 1",
			parameters: parameters,
			location: "body",
		},
		err_73: {
			code: "err_73",
			failMsg: "InvalidDetails",
			message: "Please fill required details",
			parameters: parameters,
			location: "body",
		},
		err_75: {
			code: "err_75",
			failMsg: "InvalidDetails",
			message: "Please enter valid login type",
			parameters: parameters,
			location: "body",
		},
		err_76: {
			code: "err_76",
			failMsg: "NoDataFound",
			message: "User data not found",
			parameters: parameters,
			location: "body",
		},
		err_77: {
			code: "err_77",
			failMsg: "NoDataFound",
			message: "User not registered",
			parameters: parameters,
			location: "body",
		},
		err_78: {
			code: "err_78",
			failMsg: "NoDataFound",
			message: "Appointment data not found",
			parameters: parameters,
			location: "body",
		},
		err_79: {
			code: "err_79",
			failMsg: "InvalidDetails",
			message: "Please enter valid date",
			parameters: parameters,
			location: "body",
		},
		err_80: {
			code: "err_80",
			failMsg: "InvalidDetails",
			message: "Please enter valid sendBy value 0 or 1",
			parameters: parameters,
			location: "body",
		},
		err_81: {
			code: "err_81",
			failMsg: "InvalidDetails",
			message: "Please enter valid payment id",
			parameters: parameters,
			location: "body",
		},
		err_82: {
			code: "err_82",
			failMsg: "InvalidDetails",
			message: "Invoice data not found",
			parameters: parameters,
			location: "body",
		},
		err_83: {
			code: "err_83",
			failMsg: "InvalidDetails",
			message: "Please add rating between 1 to 5",
			parameters: parameters,
			location: "body",
		},
		err_84: {
			code: "err_84",
			failMsg: "InvalidDetails",
			message: "Reviews data not found",
			parameters: parameters,
			location: "body",
		},
		err_85: {
			code: "err_85",
			failMsg: "InvalidDetails",
			message: "Your account is deactivated, please login and activate your account",
			parameters: parameters,
			location: "body",
		},
		err_86: {
			code: "err_86",
			failMsg: "InvalidDetails",
			message: "Banners data not found",
			parameters: parameters,
			location: "body",
		},
		err_87: {
			code: "err_87",
			failMsg: "InvalidDetails",
			message: "Please enter valid bannerId",
			parameters: parameters,
			location: "body",
		},
		err_88: {
			code: "err_88",
			failMsg: "DataNotFound",
			message: "Banner details not found",
			parameters: parameters,
			location: "params",
		},
		err_89: {
			code: "err_89",
			failMsg: "InvalidDetails",
			message: "Password should not be same as the previous password",
			parameters: parameters,
			location: "params",
		},
		err_90: {
			code: "err_90",
			failMsg: "InvalidDetails",
			message: "Deleted user",
			parameters: parameters,
			location: "params",
		},

		err_94: {
			code: "err_94",
			failMsg: "Invalid",
			message: "Name already exist, please try another name",
			parameters: parameters,
			location: "body",
		},
		err_95: {
			code: "err_95",
			failMsg: "Invalid",
			message: "Details not found",
			parameters: parameters,
			location: "body",
		},
		err_96: {
			code: "err_96",
			failMsg: "Invalid",
			message: "Appointment details not found for payment.",
			parameters: parameters,
			location: "body",
		},
		err_97: {
			code: "err_97",
			failMsg: "Invalid",
			message: "Your account is suspened by admin.",
			parameters: parameters,
			location: "body",
		},
		err_98: {
			code: "err_98",
			failMsg: "AlreadyExists",
			message: "therapiName or arabicName name already exists",
			parameters: parameters,
			location: "body",
		},
		err_119: {
			code: "err_119",
			failMsg: "InvalidISO",
			message: "Invalid phone number",
			parameters: parameters,
			location: "body",
		},
		err_120: {
			code: "err_120",
			failMsg: "AlreadyExists",
			message: "phone number already exists",
			parameters: parameters,
			location: "body",
		},
		err_121: {
			code: "err_121",
			failMsg: "isSuspend field required",
			message: "isSuspend valid value 0 or 1",
			parameters: parameters,
			location: "body",
		},
		err_122: {
			code: "err_122",
			failMsg: "field required",
			message: "suspendReason field required ",
			parameters: parameters,
			location: "body",
		},
		err_123: {
			code: "err_123",
			failMsg: "field required",
			message: "suspendSubject field required ",
			parameters: parameters,
			location: "body",
		},
		err_124: {
			code: "err_124",
			failMsg: "InvalidDetails",
			message: "Please provide valid action 1 or 3",
			parameters: parameters,
			location: "body",
		},
		err_125: {
			code: "err_125",
			failMsg: "NoDataFound",
			message: "admin data not found",
			parameters: parameters,
			location: "body",
		},
		err_126: {
			code: "err_126",
			failMsg: "NoDataFound",
			message: "patients data not found",
			parameters: parameters,
			location: "body",
		},
		err_127: {
			code: "err_127",
			failMsg: "NoDataFound",
			message: "resources data not found",
			parameters: parameters,
			location: "body",
		},
		err_128: {
			code: "err_128",
			failMsg: "NoDataFound",
			message: "doctors data not found",
			parameters: parameters,
			location: "body",
		},
		err_129: {
			code: "err_129",
			failMsg: "NoDataFound",
			message: "languages data not found",
			parameters: parameters,
			location: "body",
		},
		err_130: {
			code: "err_130",
			failMsg: "AlreadyExists",
			message: "language name already exists",
			parameters: parameters,
			location: "body",
		},
		err_131: {
			code: "err_131",
			failMsg: "InvalidDetails",
			message: "Please enter valid language id",
			parameters: parameters,
			location: "body",
		},
		err_132: {
			code: "err_132",
			failMsg: "InvalidDetails",
			message: "You used the social login to sign up.",
			parameters: parameters,
			location: "body",
		},
		err_133: {
			code: "err_133",
			failMsg: "dataNotFound",
			message: "No data found",
			parameters: parameters,
			location: "body",
		},
		err_134: {
			code: "err_134",
			failMsg: "InvalidDetails",
			message: "Please provide valid week day name",
			parameters: parameters,
			location: "body",
		},
		err_135: {
			code: "ER-err_135",
			fail_msg: "Invalid Details",
			message: "user is not in chat",
			parameters: parameters,
			location: "body",
		},
		err_136: {
			code: "ER-136",
			fail_msg: "Invalid Details",
			message: "user not found",
			parameters: parameters,
			location: "body",
		},

		err_106: {
			code: "ER-106",
			fail_msg: "Invalid Details",
			message: "no chat history found",
			parameters: parameters,
			location: "body",
		},
		err_137: {
			code: "err_137",
			failMsg: "Invalid",
			message: "Please enter valid value",
			parameters: parameters,
			location: "body",
		},
		err_138: {
			code: "err_138",
			failMsg: "Invalid",
			message: "somethings went wrong notification not send",
			parameters: parameters,
			location: "body",
		},
		err_140: {
			code: "err_140",
			failMsg: "invalidRequest",
			message: "Something went wrong while connecting, please try again",
			parameters: parameters,
			location: "body",
		},
		err_141: {
			code: "err_141",
			failMsg: "invalidRequest",
			message: "Patient is Offline",
			parameters: parameters,
			location: "body",
		},
		err_142: {
			code: "err_142",
			failMsg: "invalidRequest",
			message: "Sorry the therapist might be running a bit late,he'll be with you soon",
			parameters: parameters,
			location: "body",
		},
		err_143: {
			code: "err_143",
			failMsg: "invalidRequest",
			message: "Call is already started",
			parameters: parameters,
			location: "body",
		},
		err_144: {
			code: "err_144",
			failMsg: "invalidRequest",
			message: "Chat is already started",
			parameters: parameters,
			location: "body",
		},
		err_145: {
			code: "err_145",
			failMsg: "InvalidDetails",
			message: "Please enter valid time zone",
			parameters: parameters,
			location: "body",
		},
		err_146: {
			code: "err_146",
			failMsg: "InvalidDetails",
			message: "Please enter required details",
			parameters: parameters,
			location: "body",
		},
		err_147: {
			code: "err_147",
			failMsg: "DataNotFound",
			message: "Therapy not found",
			parameters: parameters,
			location: "body",
		},
		err_148: {
			code: "err_148",
			failMsg: "invalidId",
			message: "Please enter valid therapi id",
			parameters: parameters,
			location: "body",
		},
		err_149: {
			code: "err_149",
			failMsg: "AlreadyExists",
			message: "Therapy already exists",
			parameters: parameters,
			location: "body",
		},
		err_150: {
			code: "err_150",
			failMsg: "InvalidDetails",
			message: "Please enter valid reportId",
			parameters: parameters,
			location: "body",
		},
		err_151: {
			code: "err_151",
			failMsg: "DataNotFound",
			message: "Report details not found",
			parameters: parameters,
			location: "params",
		},
		err_152: {
			code: "err_152",
			failMsg: "InvalidDetails",
			message: "Please enter valid report id",
			parameters: parameters,
			location: "body",
		},
		err_153: {
			code: "err_153",
			failMsg: "AlreadyBooked",
			parameters: parameters,
			location: "body",
		},
		err_154: {
			code: "err_154",
			failMsg: "invalidOtp",
			message: "Please enter valid OTP",
			parameters: parameters,
			location: "body",
		},
		err_155: {
			code: "err_155",
			failMsg: "otpRequired",
			message: "Otp is Required",
			parameters: parameters,
			location: "body",
		},
		err_156: {
			code: "err_156",
			failMsg: "otpExpired",
			message: "Otp is expired",
			parameters: parameters,
			location: "body",
		},
		err_157: {
			code: "err_157",
			failMsg: "invalidDetails",
			message: "Please select valid appointment date",
			parameters: parameters,
			location: "body",
		},
		err_158: {
			code: "err_158",
			failMsg: "invalidDetails",
			message: "Please set valid isAppointment flag 0 or 1",
			parameters: parameters,
			location: "body",
		},
		err_159: {
			code: "err_159",
			failMsg: "alreadyEnabled",
			message: "you have already enabled consult now",
			parameters: parameters,
			location: "body",
		},
		err_160: {
			code: "err_159",
			failMsg: "alreadyDisabled",
			message: "you have already disabled consult now",
			parameters: parameters,
			location: "body",
		},
	};
	return obj[key];
}

module.exports = {
	successOrErrors,
};
